export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_PAGE_SUCCESS = 'CHANGE_PAGE_SUCCESS';

export const GET_POST = 'GET_POST';

export const SHOW_MODAL_STATE = 'SHOW_MODAL_STATE';
export const HIDDEN_MODAL_STATE = 'HIDDEN_MODAL_STATE';
